routes.py
from flask import Blueprint, render_template, request, redirect, session, abort, jsonify, url_for, flash
from models import Estate, User, Message, Administrator, ViewHistory, Favorite, db
from wtforms import PasswordField, EmailField, StringField, SubmitField, BooleanField
from wtforms.validators import Email, DataRequired, EqualTo, ValidationError, Length, Regexp
from flask_wtf import FlaskForm
import re
from functools import wraps
from sqlalchemy.exc import SQLAlchemyError
from werkzeug.security import generate_password_hash
from datetime import timedelta
import logging

main_bp = Blueprint('main', __name__)

logging.basicConfig(
    filename='app.log',  # Имя файла, в который будут записываться логи
    level=logging.DEBUG,  # Уровень логирования
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'  # Формат логов
)

@main_bp.route("/")
def hello_dreamhouse():
    try:
        estate = Estate.query.all()
        page = request.args.get('page', 1, type=int)
        per_page = 10
        start = (page - 1) * per_page
        end = start + per_page
        total_pages = (len(estate) + per_page - 1) // per_page

        estates_on_page = estate[start:end]

        return render_template('home.html', estate=estate, estates_on_page=estates_on_page, total_pages=total_pages)
    except Exception as e:
        return render_template('error.html', error=str(e)), 500

@main_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user:
            flash('Этот email уже используется, пожалуйста, выберите другой.', 'danger')
            return redirect(url_for('main.register'))
        
        new_user = User(
            name=form.name.data,
            email=form.email.data,
            password=generate_password_hash(form.password.data)
        )
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрированы!', 'success')
        
        session['logged_in'] = True
        session['user_id'] = new_user.id
        session['user_name'] = new_user.name
        session['user_email'] = new_user.email
        
        if form.remember_me.data:
            session.permanent = True
            main_bp.permanent_session_lifetime = timedelta(days=30)
        else:
            session.permanent = False
        
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form)

class RegistrationForm(FlaskForm):
    name = StringField('Имя', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Этот email уже используется, пожалуйста, выберите другой.')

    password = PasswordField('Пароль', validators=[
        DataRequired(),
        Length(min=8, max=20, message='Пароль должен быть от 8 до 20 символов'),
        Regexp('^[a-zA-Z0-9]*$', message='Пароль должен содержать только латинские буквы и цифры')
    ])
    confirm_password = PasswordField('Повторите пароль', validators=[
        DataRequired(),
        EqualTo('password', message='Пароли должны совпадать')
    ])
    remember_me = BooleanField('Запомнить меня')  # Добавлено поле для "Запомнить меня"
    submit = SubmitField('Зарегистрироваться')

@main_bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')
        remember_me = request.form.get('remember_me')

        logging.debug(f"Attempting login with email: {email}")
        
        admin = Administrator.query.filter_by(email=email).first()
        if admin:
            logging.debug(f"Administrator found: {admin.email}")
        else:
            logging.debug("No administrator found with this email")
        
        if admin and admin.check_password(password):
            logging.debug("Password check passed for admin")
            session['admin_logged_in'] = True
            session['admin_id'] = admin.id
            if remember_me:
                session.permanent = True
                main_bp.permanent_session_lifetime = timedelta(days=30)
            else:
                session.permanent = False
            return redirect("/admin")
        
        user = User.query.filter_by(email=email).first()
        if user:
            logging.debug(f"User found: {user.email}")
        else:
            logging.debug("No user found with this email")
        
        if user and user.check_password(password):
            logging.debug("Password check passed for user")
            session['user_logged_in'] = True
            session['user_id'] = user.id
            session['user_name'] = user.name
            session['user_email'] = user.email
            if remember_me:
                session.permanent = True
                main_bp.permanent_session_lifetime = timedelta(days=30)
            else:
                session.permanent = False
            return redirect('/')
        
        logging.debug("Password check failed for both admin and user")
        return redirect("/login?failed=True")
    else:
        return render_template("login.html")

def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'admin_logged_in' not in session or not session['admin_logged_in']:
            abort(403)  # Возвращает ошибку 403 Forbidden
        return f(*args, **kwargs)
    return decorated_function

@main_bp.route("/logout")
def logout():
    session.clear()
    return redirect("/login")

@main_bp.route("/contacts")
def contact_details():
    return render_template('contacts.html')

@main_bp.route("/about-us")
def about_company():
    return render_template('aboutus.html')

@main_bp.route("/place_ad")
def place_ad():
    return render_template('place_ad.html')

@main_bp.route("/api/estate")
def list_estate():
    try:
        estates = Estate.query.all()
        return jsonify(estate=estates)
    except Exception as e:
        return jsonify(error=str(e)), 500

@main_bp.route("/estateitem/<int:id>")
def show_estate(id):
    estate_item = Estate.query.get(id)
    if not estate_item:
        return "Not Found", 404

    is_favorite = False
    if session.get('user_logged_in'):
        user_id = session.get('user_id')
        if user_id:  
            # Проверяем, есть ли недвижимость в избранном для текущего пользователя
            favorite = Favorite.query.filter_by(user_id=user_id, estate_id=estate_item.id).first()
            if favorite:
                is_favorite = True

    
    # Автоматическое добавление в историю просмотров
    if session.get('user_logged_in'):
        user_id = session.get('user_id')
        if user_id:  
            history = ViewHistory(user_id=user_id, estate_id=id)
            db.session.add(history)
            db.session.commit()
        else:
            print("В сеансе отсутствует идентификатор пользователя. Не удается добавить его в журнал просмотра.")

    return render_template('estatepage.html', estate=estate_item, is_favorite=is_favorite)

@main_bp.route("/sent-message", methods=['POST'])
def fill_in_the_form():
    try:
        data = request.form
        add_message_to_db(data)
        return render_template('sent_message.html', data=data)
    except SQLAlchemyError as e:
        return render_template('error.html', error=str(e)), 500

def add_message_to_db(data):
    try:
        if all(key in data for key in ['full_name', 'phone_number', 'email', 'message', 'page_url']):
            message = Message(
                full_name=data.get('full_name', ''),
                phone_number=data.get('phone_number', ''),
                email=data.get('email', ''),
                message=data.get('message', ''),
                page_url=data.get('page_url', '')  # Если page_url получается автоматически, он будет взят из данных формы
            )
            db.session.add(message)
            db.session.commit()
            print("Сообщение успешно добавлено в базу данных.")
        else:
            print("Отсутствуют обязательные поля в данных.")
    except SQLAlchemyError as e:
        print("Произошла ошибка при добавлении сообщения в базу данных:", str(e))
        db.session.rollback()
        raise

@main_bp.route('/search', methods=['GET'])
def search():
    bedrooms = request.args.get('bedrooms')
    estate_type = request.args.get('type')
    price_range = request.args.get('price_range')
    page = request.args.get('page', 1, type=int)
    per_page = 10

    results_query = perform_search(price_range, bedrooms, estate_type)
    total_results = results_query.count()
    results = results_query.paginate(page=page, per_page=per_page, error_out=False).items

    total_pages = (total_results + per_page - 1) // per_page

    return render_template('search_results.html', results=results, total_pages=total_pages, current_page=page)

def perform_search(price_range, bedroom, estate_type):
    query = db.session.query(Estate)
    if bedroom:
        query = query.filter_by(bedrooms=bedroom)
    if estate_type:
        query = query.filter_by(type=estate_type)
    if price_range:
        if price_range == '200000-more':
            query = query.filter(Estate.cost >= 200000)
        else:
            min_price, max_price = map(int, price_range.split('-'))
            query = query.filter(Estate.cost.between(min_price, max_price))
    return query

@main_bp.route('/user/profile')
def profile():
    if not session.get('user_logged_in') or session.get('admin_logged_in'):
        return redirect('/login')
    user_id = session.get('user_id')
    user = User.query.get(user_id)
    user_data = {
        'name': session.get('user_name'),
        'email': session.get('user_email')
    }

templates/user/edit_profile.html
<!DOCTYPE html>
<html>

<head>
    {% include 'bootstrap.html' %}
    <title>Редактировать профиль</title>
    <style>
        .sidebar {
            position: fixed;
            top: 60px;
            /* adjust based on your navbar height */
            left: 0;
            height: 100%;
            width: 200px;
            padding: 20px;
            background-color: #f8f9fa;
            border-right: 1px solid #ddd;
        }

        .main-content {
            margin-left: 220px;
            padding: 20px;
        }
    </style>
</head>

<body>
    {% include 'nav.html' %}
    <div class="sidebar">
        <h3>Меню</h3>
        <a href="/user/profile/edit" class="btn btn-primary btn-block mb-2">Редактировать профиль</a>
        <a href="/user/favorites" class="btn btn-secondary btn-block mb-2">Избранное</a>
        <a href="/user/history" class="btn btn-secondary btn-block mb-2">История поиска</a>
        <a href="/logout" class="btn btn-danger btn-block">Выход</a>
    </div>
    <div class="main-content">
        <h1>Редактировать профиль</h1>
        <form method="post" action="{{ url_for('main.edit_profile') }}">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control") }}
                {% if form.name.errors %}
                <div class="alert alert-danger">
                    {% for error in form.name.errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-label") }}
                {{ form.email(class="form-control") }}
                {% if form.email.errors %}
                <div class="alert alert-danger">
                    {% for error in form.email.errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-label") }}
                {{ form.password(class="form-control") }}
                {% if form.password.errors %}
                <div class="alert alert-danger">
                    {% for error in form.password.errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-label") }}
                {{ form.confirm_password(class="form-control") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-danger">
                    {% for error in form.confirm_password.errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Сохранить изменения</button>
        </form>
        <a href="/user/profile" class="btn btn-secondary mt-2">Отменить</a>
    </div>
    {% include 'footer.html' %}
</body>

</html>

templates/user/favorites.html
<!DOCTYPE html>
<html>

<head>
    {% include 'bootstrap.html' %}
    <title>Избранное</title>
    <style>
        .sidebar {
            position: fixed;
            top: 60px;
            left: 0;
            height: 100%;
            width: 200px;
            padding: 20px;
            background-color: #f8f9fa;
            border-right: 1px solid #ddd;
        }

        .main-content {
            margin-left: 220px;
            padding: 20px;
        }

        .img-responsive {
            max-width: 100%;
            height: auto;
        }

        .estate-item {
            margin-bottom: 16px;
            padding-bottom: 4px;
            border-bottom: 1px solid #ccc;
            display: flex;
        }

        .estate-item-image {
            flex: 1;
            padding-right: 20px;
        }

        .estate-item-details {
            flex: 3;
        }

        .estate-item-details h4 {
            color: rgb(120, 120, 120);
            margin-bottom: 4px;
        }
    </style>
</head>

<body>
    {% include 'nav.html' %}
    <div class="sidebar">
        <h3>Меню</h3>
        <a href="/user/profile/edit" class="btn btn-primary btn-block mb-2">Редактировать профиль</a>
        <a href="/user/favorites" class="btn btn-secondary btn-block mb-2">Избранное</a>
        <a href="/user/history" class="btn btn-secondary btn-block mb-2">История просмотров</a>
        <a href="/logout" class="btn btn-danger btn-block">Выход</a>
    </div>
    <div class="main-content">
        <h1>Избранное</h1>
            <a href="/user/profile">Назад в профиль</a>
        {% for favorite in favorites.items %}
        <div class="estate-item">
            <div class="estate-item-image">
                {% if favorite.estate.photo %}
                <a href="{{ url_for('main.show_estate', id=favorite.estate.id) }}">
                    <img src="{{ url_for('static', filename='uploads/' + favorite.estate.photo.split(',')[0]) }}"
                        class="img-responsive" alt="Фото недвижимости">
                </a>
                {% else %}
                <p>Нет фотографий</p>
                {% endif %}
            </div>
            <div class="estate-item-details">
                <h4>{{ favorite.estate.type }}</h4>
                <div><b>Местоположение:</b> {{ favorite.estate.location }}</div>
                <div><b>Комнаты:</b> {{ favorite.estate.bedrooms }}</div>
                {% if favorite.estate.cost is not none %}
                <div><b>Стоимость:</b> {{ favorite.estate.cost }} {{ favorite.estate.currency }}</div>
                {% endif %}
                <div class="mt-2">
                    <a href="/estateitem/{{ favorite.estate.id }}" type="button"
                        class="btn btn-outline-primary">Подробнее</a>
                        <form action="/remove_from_favorites/{{ favorite.estate.id }}" method="POST" id="remove-form">
                            <button type="submit" class="btn btn-secondary">Удалить из избранного</button>
                        </form>
                </div>
            </div>
        </div>
        {% endfor %}
        <!-- Пагинация -->
        <div class="pagination">
            {% if favorites.has_prev %}
            <a href="{{ url_for('main.favorites', page=favorites.prev_num) }}">Предыдущая</a>
            {% endif %}
            &nbsp; <!-- Пробел между кнопками -->
            {% if favorites.has_next %}
            <a href="{{ url_for('main.favorites', page=favorites.next_num) }}">Следующая</a>
            {% endif %}
        </div>
    </div>
    {% include 'footer.html' %}
</body>

</html>

templates/user/history.html
<!DOCTYPE html>
<html>

<head>
    {% include 'bootstrap.html' %}
    <title>История просмотров</title>
    <style>
        .sidebar {
            position: fixed;
            top: 60px;
            left: 0;
            height: 100%;
            width: 200px;
            padding: 20px;
            background-color: #f8f9fa;
            border-right: 1px solid #ddd;
        }

        .main-content {
            margin-left: 220px;
            padding: 20px;
        }

        .estate-item {
            margin-bottom: 16px;
            padding-bottom: 4px;
            border-bottom: 1px solid #ccc;
            display: flex;
        }

        .estate-item-image {
            flex: 1;
            padding-right: 20px;
        }

        .estate-item-details {
            flex: 3;
        }

        .estate-item-details h4 {
            color: rgb(120, 120, 120);
            margin-bottom: 4px;
        }

        .img-responsive {
            max-width: 100%;
            height: auto;
        }

        .clear-history-btn {
            margin-bottom: 20px;
        }
    </style>
</head>

<body>
    {% include 'nav.html' %}
    <div class="sidebar">
        <h3>Меню</h3>
        <a href="/user/profile/edit" class="btn btn-primary btn-block mb-2">Редактировать профиль</a>
        <a href="/user/favorites" class="btn btn-secondary btn-block mb-2">Избранное</a>
        <a href="/user/history" class="btn btn-secondary btn-block mb-2">История просмотров</a>
        <a href="/logout" class="btn btn-danger btn-block">Выход</a>
    </div>
    <div class="main-content">
        <h1>Вы недавно просматривали</h1>
        <form action="/user/clear_history" method="POST" class="clear-history-btn">
            <button type="submit" class="btn btn-danger">Очистить историю просмотров</button>
        </form>
        <a href="/user/profile">Назад в профиль</a>
        <hr>
        {% if history.items %}
        {% for history_item in history.items %}
        <div class="estate-item">
            <div class="estate-item-image">
                {% if history_item.estate.photo %}
                <a href="{{ url_for('main.show_estate', id=history_item.estate.id) }}">
                    <img src="{{ url_for('static', filename='uploads/' + history_item.estate.photo.split(',')[0]) }}"
                        class="img-responsive" alt="Фото недвижимости">
                </a>
                {% else %}
                <p>Нет фотографий</p>
                {% endif %}
            </div>
            <div class="estate-item-details">
                <h4>{{ history_item.estate.type }}</h4>
                <div><b>Местоположение:</b> {{ history_item.estate.location }}</div>
                <div><b>Комнаты:</b> {{ history_item.estate.bedrooms }}</div>
                {% if history_item.estate.cost is not none %}
                <div><b>Стоимость:</b> {{ history_item.estate.cost }} {{ history_item.estate.currency }}</div>
                {% endif %}
                <div class="mt-2">
                    <a href="/estateitem/{{ history_item.estate.id }}" type="button"
                        class="btn btn-outline-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <!-- Пагинация -->
        <div class="pagination">
            {% if history.has_prev %}
            <a href="{{ url_for('main.view_history', page=history.prev_num) }}">Предыдущая</a>
            {% endif %}
            &nbsp; <!-- Пробел между кнопками -->
            {% if history.has_next %}
            <a href="{{ url_for('main.view_history', page=history.next_num) }}">Следующая</a>
            {% endif %}
        </div>
        {% else %}
        <p>История просмотров пуста.</p>
        {% endif %}
    </div>
    {% include 'footer.html' %}
</body>

</html>

templates/user/profile.html
<!DOCTYPE html>
<html>

<head>
    {% include 'bootstrap.html' %}
    <title>Мой профиль</title>
    <style>
        .sidebar {
            position: fixed;
            top: 60px;
            left: 0;
            height: 100%;
            width: 200px;
            padding: 20px;
            background-color: #f8f9fa;
            border-right: 1px solid #ddd;
        }

        .main-content {
            margin-left: 220px;
            padding: 20px;
        }
    </style>
</head>

<body>
    {% include 'nav.html' %}
    <div class="sidebar">
        <h3>Меню</h3>
        <a href="/user/profile/edit" class="btn btn-primary btn-block mb-2">Редактировать профиль</a>
        <a href="/user/favorites" class="btn btn-secondary btn-block mb-2">Избранное</a>
        <a href="/user/history" class="btn btn-secondary btn-block mb-2">История поиска</a>
        <a href="/logout" class="btn btn-danger btn-block">Выход</a>
    </div>
    <div class="main-content">
        <h1>Профиль</h1>
        <p>Имя: {{ user.name }}</p>
        <p>Email: {{ user.email }}</p>

        <form action="{{ url_for('main.delete_account') }}" method="post"
            onsubmit="return confirm('Вы уверены, что хотите удалить свой аккаунт? Это действие необратимо.');">
            <button type="submit" class="btn btn-danger">Удалить аккаунт</button>
        </form>
    </div>


    {% include 'footer.html' %}
</body>

</html>